anchor/programs/glam/src/instructions/manager.rs, anchor/programs/glam/src/lib.rs, anchor/programs/glam/src/state/fund.rs, anchor/tests/glam_crud.spec.ts
Need to be initialized at fund creation time
=> Support share class metadata

.github/workflows/dapp.yml, .github/workflows/pr_build.yml, web/src/app/glam/glam-data-access.tsx
1. Fix web build
3. Trigger workflow run on PRs
=> Fix web build and trigger build on PRs

anchor/programs/glam/src/instructions/manager.rs, anchor/programs/glam/src/lib.rs, anchor/programs/glam/src/state/fund.rs, anchor/target/idl/glam.json, anchor/target/types/glam.ts, anchor/tests/glam_crud.spec.ts, web/src/app/glam/glam-data-access.tsx
Define a ShareClassMetadata struct and compute its INIT_SIZE that'll be used later on in program
=> ShareClassMetadata struct for share class metadata

anchor/programs/glam/src/instructions/manager.rs, anchor/programs/glam/src/state/fund.rs, anchor/target/idl/glam.json, anchor/target/types/glam.ts, anchor/tests/glam_crud.spec.ts, web/src/app/glam/glam-data-access.tsx
1. Added to metadata fields per https://docs.google.com/spreadsheets/d/1sNKoqr48AIslZlYjDG3LZYfW4qMGb3Ak-x18mvfVLYg/edit#gid=959668688
2. Update share class mint decimals from 0 to 9
=> anchor: add more metadata fields per the spec

.github/workflows/dapp.yml, .github/workflows/pr_build.yml, api/server.js
1. return a json blob from metadata endpoint
2. update workflow files to skip runs on `api/` changes
=> api: metadata json blob

api/package.json, api/pnpm-lock.yaml, api/prices.js, api/server.js, api/tests/server.test.js
`*` should be avoided but we need to allow local tests
=> api: cors + include benchmarks from fund perf endpoint

web/src/app/glam/glam-data-access.tsx, web/src/app/products/product-page.tsx
=> web: Fetch chart data from api

anchor/tests/glam_crud.spec.ts, anchor/tests/glam_investor.spec.ts
1. some tests in `glam_crud.spec` tests were commented out, this PR brings them back.
2. `glam_investor.spec` tests were failing due to fund not being properly initialized, this PR fixes that.
=> anchor: fix tests

api/package.json, api/pnpm-lock.yaml, api/server.js, api/tests/server.test.js
Implementation based on example code at https://github.com/pyth-network/pyth-crosschain/tree/main/target_chains/ethereum/sdk/js
=> api: return real time prices

web/src/app/glam/glam-data-access.tsx, web/src/app/products/product-page.tsx
1. find all token accounts from treasury address, then compute aum from all holdings
2. get total supply from share class mint
3. nav = aum / totalShares
=> web: use real data for aum and nav

web/src/app/manage/Manage.tsx, web/src/app/products/SideActionBar.tsx, web/src/app/products/product-page.tsx, web/src/app/products/products-overview.tsx, web/src/app/ui/ui-layout.tsx, web/src/app/utils/format-number.ts
Fixed grid layout
Made Product overview page dynamic and querying the real products
Removed additional tabs from product page
=> [UI] - Fixed grid layout

anchor/programs/glam/src/instructions/investor.rs, anchor/tests/glam_investor.spec.ts
1. initial share value 10 -> 100
2. updates tests
=> anchor: update initial share value to 100

anchor/Anchor.toml, anchor/programs/glam/src/instructions/investor.rs, anchor/target/idl/glam.json, anchor/target/types/glam.ts, anchor/tests/glam_crud.spec.ts, anchor/tests/glam_investor.spec.ts, web/src/app/glam/glam-data-access.tsx
1. use anchor's init-if-needed feature to automatically create share ATA when the account doesn't exist
2. increase CU limit for subscribe function
=> anchor: create share ATA when it doesn't exist

README.md, web/src/app/manage/Assets.tsx, web/src/app/manage/CreateProduct.tsx, web/src/app/manage/Manage.tsx, web/src/app/products/SideActionBar.tsx, web/src/app/products/product-page.tsx, web/src/app/products/products-overview.tsx, web/src/app/ui/Pagination.tsx, web/src/app/ui/ui-layout.tsx, web/src/styles.scss
Fixes
-Products. Table is vertically centered, on small screen it goes out. Align to the top, let the page scroll.
- Hide Account in menu
- Create Product form. Disable assets and integrations that can't be used (everything except USDC, WSOL, WBTC, Drift)
- Subscribe tab. The input Amount is hard to use… that 0 is annoying to use
- Banner.
=> [UI] - Last rush

anchor/Anchor.toml, anchor/programs/glam/Cargo.toml, anchor/programs/glam/src/error.rs, anchor/programs/glam/src/instructions/investor.rs, anchor/target/idl/glam.json, anchor/target/types/glam.ts
1. use rust features to conditionally enable pricing account validation
2. by default `devnet` or `mainnet` are not enabled, to turn a feature on add `-- --features <feature>` to anchor commands, see https://www.soldev.app/course/env-variables
=> anchor: validate pricing accounts

web/src/app/glam/glam-data-access.tsx, web/src/app/manage/CreateProduct.tsx, web/src/app/products/product-page.tsx, web/src/app/products/products-overview.tsx
Show wallet model if user has not connected to a wallet when they
1. subscribe to a fund
2. redeem a fund
3. submit fund creation form
=> web: show wallet modal on subscribe/redeem/submit

anchor/programs/glam/src/instructions/marinade.rs, anchor/programs/glam/src/lib.rs, anchor/target/idl/glam.json, anchor/target/types/glam.ts, anchor/tests/glam_staking.spec.ts
1. Add a test for liquid unstaking
2. Check that signer == fund.manager and fund.treasury is the treasury passed in
=> anchor: add authz to marinade methods

DEVELOPER.md, api/src/main.ts, deploy_api.sh, package.json
=> api: deploy script

anchor/programs/glam/src/instructions/investor.rs, anchor/programs/glam/src/lib.rs, anchor/target/idl/glam.json, anchor/target/types/glam.ts, anchor/tests/glam_investor.spec.ts, web/src/app/glam/glam-data-access.tsx
1. Blocklist is checked first
2. If a pubkey is in both allowlist and blocklist it will be denied access
3. Check is skipped if acl is empty
=> anchor: enforce share class acls

anchor/Anchor.toml, anchor/Cargo.lock, anchor/Cargo.toml, anchor/programs/glam/Cargo.toml, anchor/programs/glam/src/instructions/investor.rs, anchor/programs/glam/src/instructions/manager.rs, anchor/programs/glam/src/instructions/marinade.rs, anchor/programs/glam/src/state/assets.rs, anchor/programs/glam/src/state/mod.rs, anchor/src/client.ts, anchor/src/client/assets.ts, anchor/src/client/base.ts, anchor/src/client/investor.ts, anchor/src/client/marinade.ts, anchor/src/clientConfig.ts, anchor/target/idl/glam.json, anchor/target/types/glam.ts, anchor/tests/glam_investor.spec.ts, api/src/main.ts
Porting investor to client SDK + various improvements
=> investor: add to js sdk

anchor/Cargo.lock, anchor/programs/glam/Cargo.toml, anchor/target/idl/glam.json, anchor/target/types/glam.ts
=> bump glam version to 0.2.3

anchor/Anchor.toml, anchor/programs/glam/src/instructions/stakepool.rs, anchor/programs/glam/src/lib.rs, anchor/src/client.ts, anchor/src/client/staking.ts, anchor/target/idl/glam.json, anchor/target/types/glam.ts, anchor/tests/glam_stakepool.spec.ts
=> sdk: stake pool methods

playground/tsconfig.json
=> playground: fix path resolving

anchor/src/react.tsx, playground/src/app/stake/page.tsx, playground/src/app/wrap/page.tsx, playground/src/components/WalletOrFundAlert.tsx, playground/src/components/ui/alert.tsx
If wallet is not connected:
If wallet is connected but has no access to any fund:
=> [playground] show error when wallet is not connected or wallet has no fund

.github/workflows/pr_test_anchor.yml
Manually triggered this run: https://github.com/glamsystems/glam/actions/runs/10868296268
=> ci: fix anchor test workflow

playground/src/app/access/components/data-table-toolbar.tsx, playground/src/app/access/components/data-table.tsx, playground/src/app/access/data/keySchema.ts, playground/src/app/access/page.tsx, playground/src/app/flows/page.tsx, playground/src/app/integrations/components/integrations-list.tsx, playground/src/app/integrations/data.tsx, playground/src/app/integrations/page.tsx, playground/src/app/openfunds/page.tsx, playground/src/components/CustomTree.tsx, playground/src/components/ToolbarTree.tsx
=> pg: integrations and access control

anchor/src/client/base.ts, anchor/src/react/glam.tsx, playground/src/app/holdings/components/data-table-row-actions.tsx, playground/src/app/holdings/page.tsx, playground/src/app/trade/page.tsx
This gets rid of the dependency on API to fetch all funds the connected wallet has access to.
=> pg: fetch all funds locally

anchor/src/client/jupiter.ts, playground/src/app/page.tsx, playground/src/app/trade/page.tsx, playground/src/app/wrap/page.tsx, playground/src/components/ui/button.tsx
Added a new prop `loading` to the button component. When transactions are pending we set the button to the loading state and disable it, until tx is completed/failed/aborted.
=> pg: show loading icon while tx is pending

anchor/src/client/base.ts, anchor/src/error.ts, anchor/src/index.ts, playground/src/app/trade/page.tsx, playground/src/app/wrap/page.tsx, playground/src/lib/error.ts
=> pg: parse tx error for user friendly message

anchor/src/client/jupiter.ts, playground/src/app/trade/page.tsx, playground/src/components/AssetInput.tsx
=> pg: show real-time quotes from jupiter

anchor/src/client/drift.ts, anchor/src/react/glam.tsx, playground/src/app/trade/page.tsx, playground/src/app/transfer/page.tsx
Implements the transfer page to deposit assets to drift user account.
=> pg: transfer page impl

anchor/src/react/glam.tsx
=> pg: fix pries not loading

playground/src/app/trade/page.tsx, playground/src/app/trade/warning.tsx
=> pg: exact-out swap warning

anchor/programs/glam/src/instructions/manager.rs, anchor/src/client.ts, anchor/src/client/fund.ts, playground/src/app/holdings/components/data-table-refresh.tsx, playground/src/app/holdings/components/data-table-row-actions.tsx, playground/src/app/holdings/components/data-table-toolbar.tsx, playground/src/app/holdings/components/data-table.tsx, playground/src/app/holdings/page.tsx, playground/src/app/trade/page.tsx
Show a Close option button when the token account has 0 balance 
Show a Swap option if token account balance is > 0
=> Show zero balances on holdings page

anchor/Cargo.lock, anchor/Cargo.toml, anchor/libs/macros/Cargo.toml, anchor/libs/macros/src/lib.rs, anchor/programs/glam/Cargo.toml, anchor/programs/glam/src/instructions/drift.rs, anchor/programs/glam/src/instructions/jupiter.rs, anchor/programs/glam/src/instructions/manager.rs, anchor/programs/glam/src/instructions/marinade.rs, anchor/programs/glam/src/instructions/stake.rs, anchor/programs/glam/src/instructions/stake_pool.rs, anchor/programs/glam/src/instructions/wsol.rs, anchor/target/idl/glam.json, anchor/target/types/glam.ts, anchor/tests/glam_crud.spec.ts, anchor/tests/glam_jupiter.spec.ts, anchor/tests/glam_marinade.spec.ts, anchor/tests/glam_policy_hook.spec.ts, anchor/tests/glam_wsol.spec.ts
I'm tired of computing treasury seeds in almost every glam method. Created a macro for it.
=> anchor: glam macro crate

playground/src/app/page.tsx, playground/src/components/AccountMenu.tsx
=> pg: default fund name

README.md, playground/src/app/(mint)/layout.tsx, playground/src/app/(playground)/layout.tsx, playground/src/app/(shared)/layout.tsx, playground/src/app/(vault)/layout.tsx, playground/src/app/layout.tsx, playground/src/components/layouts/SharedDashboardLayout.tsx
=> pg: fix toast explorer links

anchor/src/index.ts, playground/src/app/(vault)/vault/context/page.tsx, playground/src/app/(vault)/vault/holdings/page.tsx, playground/src/app/(vault)/vault/trade/page.tsx, playground/src/app/(vault)/vault/transfer/page.tsx, playground/src/components/PageAccess.tsx, playground/src/components/access/components/data-table.tsx, playground/src/hooks/useTokenList.ts
When the tree/list is too big we had to collapse it to see the buttons.
This change make the tree/list div scrollable.
=> pg: scrollable access rights list & vault context page

anchor/src/models.ts, anchor/src/react/glam.tsx, anchor/src/utils/helpers.ts, playground/src/app/(mint)/mint/create/createMintForm.tsx, playground/src/app/(playground)/playground/products/[product]/page.tsx, playground/src/app/(vault)/vault/create/page.tsx, playground/src/app/(vault)/vault/stake/components/accounts-close.tsx, playground/src/app/(vault)/vault/stake/components/accounts-merge.tsx, playground/src/app/(vault)/vault/stake/components/tickets-claim.tsx, playground/src/components/AccountMenu.tsx
=> pg: account menu improvements

anchor/src/client/base.ts, anchor/src/client/marinade.ts, anchor/src/client/staking.ts, anchor/src/clientConfig.ts, anchor/src/glamExports.ts, anchor/src/react/cluster-provider.tsx, anchor/src/react/glam.tsx, anchor/src/react/index.tsx, cli/src/main.ts, cli/src/utils.ts, playground/src/app/(playground)/playground/cluster/page.tsx, playground/src/app/(shared)/settings/page.tsx, playground/src/app/layout.tsx, playground/src/components/ExplorerLink.tsx, playground/src/components/wallet-provider.tsx
Easier to test vault creation and acls etc using devnet.
=> pg: devnet support

anchor/programs/glam/src/instructions/jupiter.rs, anchor/src/client/jupiter.ts, anchor/target/idl/glam.json, anchor/target/types/glam.ts
This reverts commit b02960a85d91e61569b7a4c5b0d91af74f997e55.
=> Revert "Jupiter update (#391)"

gui/src/app/(vault)/vault/holdings/page.tsx
=> gui: update vault name on details page

anchor/deps/drift/drift.json, anchor/programs/glam/src/cpi_autogen/config.json, anchor/programs/glam/src/cpi_autogen/drift.rs, anchor/programs/glam/src/lib.rs, anchor/target/idl/glam.json, anchor/target/types/glam.ts
- **anchor: update drift autogen code**
- **update drift idl**
=> anchor: update drift cpi autogen

anchor/programs/glam/src/cpi_autogen/config.yaml, anchor/programs/glam/src/cpi_autogen/drift.rs, anchor/programs/glam/src/instructions/drift.rs, anchor/src/client/drift.ts, anchor/target/idl/glam.json, anchor/target/types/glam.ts, anchor/tests/glam_drift.spec.ts
- Use compact yaml for cpi autogen config file
- Update drift cpi autogen code
=> anchor: cpi autogen drift update

anchor/src/client/drift.ts, gui/src/app/(vault)/vault/holdings/page.tsx, gui/src/app/(vault)/vault/integrations/policies/drift-policies.tsx, gui/src/app/(vault)/vault/integrations/policies/jupiter-policies.tsx, gui/src/components/DynamicForm.tsx, gui/src/components/SlippageInput.tsx, gui/src/data/glamRiskSchema.json
- Fix holdings skeleton & slippage input
- Fix dynamic form rendering on switching access control models
- Implement policy update of delegate account
=> gui: drift delegate account policies

anchor/programs/glam/src/state/assets.rs, anchor/src/client/assets.ts, anchor/src/client/marinade.ts, gui/src/app/(vault)/vault/holdings/page.tsx, gui/src/app/(vault)/vault/stake/page.tsx
- Add BNSOL & remove mallowSOL
- Marinade ticket claimable if it's due and new epoch >= 30min
=> gui: stake page fix
